### PR TITLE
added ability to save layer mask as PNG

### PR DESCRIPTION
**Pull request by rtf-const**
Methods maskToPng and saveMaskAsPng was added for save layer mask as PNG image

### CODE REVIEW

**Comment by fabulousduck** [comment]
Hey @rtf-const.

Thank you for taking the time to make a PR, it is always appriciated.
I will review it and add @meltingice so he can have a look too.

Once we both agree on this being a good addition it will be merged.

Regards, Duck

**Comment by rtf-const** [comment]
This functionality is already merged in https://github.com/meltingice/psd.js/pull/139

**Comment by tinypoint** [comment]
But I can not get maskToPng function in last version npm package 3.2.0.

**Comment by rtf-const** [comment]
New version of psd.js wasn't released since July 2017. It's look like @meltingice is unable to maintain it anymore. See #140

**Pull request closed without merging**
