### PR TITLE
Update build system & Update dependencies & Fix mask bug

### PR DESCRIPTION
**Pull request by laoshu133**
There has some changes:

- Update build system to webpack, and use umd output
- Update some dependencies
- Fix mask read flags bug
- Add friendly scripts compile code and release to npm

### CODE REVIEW

**Comment by laoshu133** [comment]
psd.js is a large module, we need a es5 code for building, not just the dist file, so the project can generate a source map and do not need to rely on coffee-loader;
webpack not necessary, but if webpack we will get a more elegant build system, and allow more people to understand

**Comment by edrpls** [comment]
@laoshu133 you're right, it will be better than the current build process, thanks

**Comment by joliejuke-orga** [comment]
Looks nice @laoshu133 , great work.

Does someone know if meltingice still work on this project?
I find bugs with 'solidColor', maybe I should fork your project and try to fix it.

The bug is:
A shape layer with a border does not have anymore a solidColor

Best regards.

**Comment by laoshu133** [comment]
@joliejuke-orga  You can try fork and fix it, or provide a demo

**Comment by meltingice** [comment]
I like where this is heading. I'm starting on a fresh vanilla JS branch now because I want to get rid of the Coffeescript dependency and start using Webpack.

**Pull request closed without merging**
