### PR TITLE
get more font's data via psd-enginedata

### PR DESCRIPTION
**Pull request by forsigner**
psd.js miss some font's data，I think we should get more

### CODE REVIEW

**Comment by fabulousduck** [comment]
@forsigner Thanks for the PR. Have you tested this ? Can you confirm this works ?

**Comment by fabulousduck** [comment]
@meltingice after having tested this briefly this PR does not seem to break any other functionality and can be merged. i would however advice you look through this yourself to see if you can spot anything. 

This PR itself adds quite a lot of helpful data, so if it looks good to you, this can definitely be merged

**Comment by forsigner** [comment]
@fabulousduck thx~

**Comment by forsigner** [comment]
This repos still be maintained...  Orz

**Comment by fabulousduck** [comment]
@forsigner this repo is being mainained as of late, the owner @meltingice is busy at work on a vanilla js rework of the entire project, meanwhile, i keep tabs on issues, and PR's people make.

I can't give any time frame when the vanilla rework will be done as this is completely up to @meltingice.

**Pull request merged**
